### ISSUE TITLE
Lack of flexible prefix search

### ISSUE THREAD

**Issue by r8d8** [r8d8/nem-toolchain#52]
Provide functionality to search user prefix after first chain specific letters.

Example: 
`nem --chain testnet account vanity REC`

Current: 
panic: incorrect prefix 'TREC'

Expected:
Return first found address that include `REC` after chain specific letters - TAREC..., TBREC...,

**Comment by dulanov** [comment]
For me it can look like `nem --chain testnet account vanity --offset 1 REC` or `nem --chain testnet account vanity _REC`.
